name: "example-cron-action"
on:
  schedule:
    - cron:  '*/6 * * * *'    # At every 6th minute

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.DELAYED_JOB_CHECKOUT_REF }} # SHA that triggered your original job 

      - name: Do some work
        run: echo $GITHUB_SHA

      # If job finished successfully, remove the workflow file (and tag if necessary)
      - name: Remove scheduled job
        uses: cardinalby/unschedule-job-action@v1
        if: github.run_number > 10
        with:
          ghToken: ${{ secrets.WORKFLOWS_TOKEN }} 
  
