name: example-cron-action
'on':
  schedule:
    - cron: '*/15 * * * *'
jobs:
  singleJobName:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ env.DELAYED_JOB_CHECKOUT_REF }}'
      - name: Do some work
        run: echo $GITHUB_SHA
      - name: Remove scheduled job
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: '${{ secrets.WORKFLOWS_TOKEN }}'
    env:
      DELAYED_JOB_CHECKOUT_REF: f5b7cd34f7995fd7c008d248cd5f1e44d06df9f1
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: .github/workflows/example-f5b7cd34f7995fd7c008d248cd5f1e44d06df9f1.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: master
