# This is a basic workflow to help you get started with Actions.


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       # Check-out your repository.
#       - name: Checkout
#         uses: actions/checkout@v2


on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ post-esa ]
  pull_request:
    branches: [ post-esa ]

name: Build and Deploy a Container
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: hello-cloud-run
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ccbd-318506
        service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t gcr.io/ccbd-318506/nodeapp
        docker push gcr.io/ccbd-318506/nodeapp
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0.4.0
      with:
        service: nodeapp
        image: gcr.io/ccbd-318506/nodeapp
        region: ${{ env.REGION }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}