name: Schedule

# Controls when the action will run. 
on: # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main,heroku ]
  pull_request:
    branches: [ main,heroku ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: schedule
      - uses: cardinalby/schedule-job-action@v1
        with:
          ghToken: ${{ secrets.WORKFLOWS_TOKEN }}
          templateYmlFile: '.github/workflows/main-workflow.yml'
